title       = "google"
baseURL     = "https://google-cli.tamnd.com/"
description = "Google search suggestions and news headlines"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/google-cli"
